# Generated by Django 4.0.3 on 2022-03-31 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('psu_score', models.IntegerField(default=0)),
                ('university', models.CharField(max_length=200)),
                ('gpa_score', models.FloatField(default=0)),
                ('job', models.CharField(max_length=200)),
                ('salary', models.FloatField(default=0)),
                ('promotion', models.BooleanField(default=0)),
                ('hospital', models.CharField(max_length=200)),
                ('medical_debt', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=200)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccessTokenRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=200)),
                ('nonce', models.CharField(max_length=200)),
                ('expiration', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authyapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='AccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=200)),
                ('scopes', models.CharField(max_length=200)),
                ('expiration', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authyapp.user')),
            ],
        ),
    ]
