# Generated by Django 4.0.3 on 2022-03-31 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authyapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accesstoken',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='accesstokenrequest',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertoken',
            old_name='user_id',
            new_name='user',
        ),
    ]
