# Generated by Django 4.0.3 on 2022-04-02 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authyapp', '0002_rename_user_id_accesstoken_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='operations',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
